# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "magpie-gem"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Amol Kelkar"]
  s.date = "2013-10-17"
  s.description = "OfficeSpace Magpie Library"
  s.email = "tech@officespace.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/base.rb",
    "lib/company.rb",
    "lib/contact.rb",
    "lib/entity.rb",
    "lib/feed.rb",
    "lib/import.rb",
    "lib/importer.rb",
    "lib/location.rb",
    "lib/magpie-gem.rb",
    "lib/media.rb",
    "lib/person.rb",
    "lib/postal_address.rb",
    "lib/property.rb",
    "lib/property_amenities.rb",
    "lib/property_built.rb",
    "lib/property_floor_load_ratio.rb",
    "lib/property_land.rb",
    "lib/property_lcs.rb",
    "lib/property_sale.rb",
    "lib/property_space.rb",
    "lib/property_space_type.rb",
    "lib/property_space_type_industrial.rb",
    "lib/property_space_type_lease.rb",
    "lib/property_space_type_office.rb",
    "lib/property_space_type_retail.rb",
    "lib/property_space_types.rb",
    "lib/rate.rb",
    "lib/unit.rb",
    "lib/unit_amenities.rb",
    "lib/unit_lease.rb",
    "lib/unit_space.rb",
    "lib/unit_space_type.rb",
    "lib/unit_space_types.rb",
    "magpie-gem.gemspec",
    "spec/magpie-gem_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/redstapler/magpie-gem"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "OfficeSpace Magpie Library"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

